// const promise = new Promise((resolve, reject)=>{
//     console.log("Inside promise!!")
//     resolve(101);
// })

// promise.then((result) => {
//     console.log(result)
// }).catch((err) => {
//     console.log(err)
// });


